# Node.js addon configuration file
# This file contains Node.js specific settings for the Node.js addon

# Node.js runtime settings
LETS_NODE_DEPS=""

# Node.js NVM settings
LETS_NODE_NVM_VERSION="v0.40.3"
LETS_NODE_NVM_URL="https://raw.githubusercontent.com/nvm-sh/nvm/${LETS_NODE_NVM_VERSION}/install.sh"

# Node.js modules to install
LETS_NODE_MODULES_FILE="${LETS_PROJ_ETC_DIR}/node-modules.txt"
