# Main LETS configuration file

# General settings
LETS_VERSION="0.1.0"
LETS_AUTHOR="fudya"
LETS_AUTHOR_EMAIL="fudyas@gmail.com"
LETS_MAINTAINER=$LETS_AUTHOR_EMAIL

# Key LETS directories
LETS_BIN_DIR="${LETS_HOME}/bin"
LETS_ETC_DIR="${LETS_HOME}/etc"
LETS_LIB_DIR="${LETS_HOME}/lib"
LETS_SRC_DIR="${LETS_HOME}/src"
LETS_STATE_DIR="${LETS_PROJ_DIR}/.lets"
LETS_TOOLS_DIR="${LETS_HOME}/tools"

# Key LETS files
LETS_CAPTURE_FILE="/tmp/lets.${USER}.capture"

# Project-level directories
LETS_PROJ_BIN_DIR="${LETS_PROJ_DIR}/bin"
LETS_PROJ_ETC_DIR="${LETS_PROJ_DIR}/etc"
LETS_PROJ_SRC_DIR="${LETS_PROJ_DIR}/src"
LETS_PROJ_TOOLS_DIR="${LETS_PROJ_DIR}/tools"
LETS_PROJ_TESTS_DIR="${LETS_PROJ_DIR}/tests"
LETS_PROJ_DIST_DIR="${LETS_PROJ_DIR}/dist"
LETS_PROJ_BUILD_DIR="${LETS_PROJ_DIR}/build"

# Key project files
LETS_PROJ_DOCKER_COMPOSE_FILE="${LETS_PROJ_ETC_DIR}/docker-compose.yml"

# Key project settings
LETS_PROJ_BUILD_FLAVOR="debug"
