# Python addon configuration file
# This file contains Python specific settings for the Python addon

# Python runtime settings
LETS_PYTHON_VERSION="3.14.2"
LETS_PY_DEPS="ruff"

# Python virtual environment settings
LETS_PYENV_ROOT="${LETS_STATE_DIR}/pyenv"
LETS_PYENV_DIST="${LETS_PYENV_ROOT}/versions/venv"

# Python package management
LETS_PYTHON_PYENV_URL="https://pyenv.run"
