# Project configuration file.
# NOTE: this file is used by LETS tools

# Project version information
LETS_PROJ_VERSION="3.0"
LETS_PROJ_NAME="SCR-3"

# Default log level for LETS commands
LETS_LOG_LEVEL=$LOG_LEVEL_DIAG

# The default build flavor for the project
LETS_PROJ_BUILD_FLAVOR="debug"
